version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: pagarme/allure-upload
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            export IMAGE_VERSION_TAG=${CIRCLE_SHA1:0:7}
            docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$IMAGE_VERSION_TAG .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            export IMAGE_VERSION_TAG=${CIRCLE_SHA1:0:7}
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_VERSION_TAG
workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master
          - publish-latest:
              requires:
                - build
              filters:
                branches:
                  only: master